### ISSUE TITLE
find better documents

### ISSUE THREAD

**Issue by lfoppiano** [Marame/M2Internship_Entity_Resolution#4]
The documents in the `document.txt` files are still too similar. Please choose more variation and remove all the documens regarding the `presidential campaing`... :-)
Same for the queries... 

For the number of documents/queries: ideally you want to have something like 50 documents and 10 queries.

**Comment by lfoppiano** [comment]
Looking at `documents.csv` and `queries.csv` there are still formatting errors and the content is still not properly choosen.

**Comment by lfoppiano** [comment]
Regarding the format I recommend to review it https://en.wikipedia.org/wiki/Comma-separated_values (for example spaces within the same record are not really allowed). This would make the parser much simpler.

**Comment by Marame** [comment]
fix#4: corrected the parsing, improved the documents content
