### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by lfoppiano** [Marame/M2Internship_Entity_Resolution#9]
Still some glitches in the documentation, see screenshots: 

By the way, there is a plugin for the MD files for intellij that can show you a preview before committing/pushing. 

<img width="1063" alt="screen shot 2017-07-17 at 17 22 29" src="https://user-images.githubusercontent.com/15426/28275584-906d6ca0-6b14-11e7-8e60-592edfb030fa.png">
<img width="1001" alt="screen shot 2017-07-17 at 17 22 36" src="https://user-images.githubusercontent.com/15426/28275585-909033e8-6b14-11e7-9b0b-93b00943a6a6.png">
<img width="975" alt="screen shot 2017-07-17 at 17 22 40" src="https://user-images.githubusercontent.com/15426/28275586-90b9188a-6b14-11e7-9db1-2ddd3a5adc11.png">

**Comment by Marame** [comment]
done
